import Link from "next/link";
import { listPatients } from "@/lib/db";
import { serviceLabel } from "@/lib/services-catalog";
import { STATUS_LABELS } from "@/lib/status";

function recordCode(id: string) { return `VT-${id.replace(/-/g, "").slice(0, 6).toUpperCase()}`; }
function formatDate(value: string) { return new Intl.DateTimeFormat("vi-VN", { day: "2-digit", month: "2-digit", year: "numeric" }).format(new Date(value)); }

export default async function Home() {
  const patients = await listPatients();
  const recent = patients.slice(0, 4);
  const ready = patients.filter((patient) => patient.model3d?.before).length;
  const today = new Date().toDateString();
  const todayCount = patients.filter((patient) => new Date(patient.createdAt).toDateString() === today).length;

  return <div className="mx-auto w-full max-w-6xl px-4 py-5 sm:px-6 sm:py-8 lg:px-10 lg:py-10">
    <section className="flex items-end justify-between gap-4"><div><p className="text-xs font-bold tracking-[0.16em] text-accent">TỔNG QUAN PHÒNG KHÁM</p><h1 className="mt-2 text-2xl font-bold tracking-tight text-card-foreground sm:text-3xl">Chào buổi sáng, Văn Trường</h1><p className="mt-1 text-sm text-muted">{todayCount > 0 ? `Hôm nay có ${todayCount} hồ sơ mới cần xử lý.` : "Sẵn sàng bắt đầu một hồ sơ tư vấn mới."}</p></div><div className="hidden rounded-2xl border border-border bg-card px-4 py-3 text-right sm:block"><p className="text-xl font-bold text-card-foreground">{patients.length}</p><p className="text-xs text-muted">Tổng hồ sơ</p></div></section>
    <Link href="/patients/new" className="group mt-6 block overflow-hidden rounded-3xl bg-[linear-gradient(125deg,#a74048,#7f3038)] p-6 text-white shadow-[0_14px_38px_rgba(127,48,56,0.24)] transition hover:-translate-y-0.5 sm:p-8"><div className="flex items-center justify-between gap-4"><div><span className="inline-flex rounded-full bg-white/15 px-3 py-1 text-[11px] font-bold tracking-wide">QUY TRÌNH MỚI</span><h2 className="mt-4 text-2xl font-bold tracking-tight sm:text-3xl">Tạo hồ sơ bệnh án</h2><p className="mt-2 max-w-md text-sm leading-6 text-white/80">Ghi nhận khách hàng, ảnh bệnh án, consent và chuẩn bị cho phiên scan 3D.</p></div><span className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl bg-white text-3xl font-light text-accent transition group-hover:scale-105">+</span></div><div className="mt-6 flex items-center gap-2 text-xs font-semibold text-white/90"><span className="h-2 w-2 rounded-full bg-[#eac2a4]" />Bắt đầu trong vài phút <span aria-hidden="true">→</span></div></Link>
    <section className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-4">{[{ value: patients.length, label: "Hồ sơ bệnh án" }, { value: ready, label: "Baseline 3D sẵn sàng" }, { value: patients.filter((p) => p.simulation).length, label: "Phương án đã lưu" }, { value: patients.filter((p) => Object.keys(p.photos).length > 0).length, label: "Có ảnh bệnh án" }].map((item) => <div key={item.label} className="rounded-2xl border border-border bg-card p-4"><p className="text-2xl font-bold text-card-foreground">{item.value}</p><p className="mt-1 text-xs leading-4 text-muted">{item.label}</p></div>)}</section>
    <section className="mt-9"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold text-card-foreground">Hồ sơ gần đây</h2><p className="mt-1 text-sm text-muted">Tiếp tục đúng quy trình của từng khách hàng.</p></div><Link href="/patients" className="text-sm font-bold text-accent">Xem tất cả</Link></div>{recent.length === 0 ? <div className="mt-4 rounded-3xl border border-dashed border-border bg-card px-5 py-10 text-center"><p className="font-semibold text-card-foreground">Chưa có hồ sơ bệnh án</p><p className="mt-1 text-sm text-muted">Tạo hồ sơ đầu tiên để bắt đầu workflow scan 3D.</p></div> : <div className="mt-4 grid gap-3 md:grid-cols-2">{recent.map((patient) => <Link key={patient.id} href={`/patients/${patient.id}`} className="rounded-2xl border border-border bg-card p-4 transition hover:border-accent/30 hover:shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="font-bold text-card-foreground">{patient.fullName}</p><p className="mt-1 text-xs text-muted">{recordCode(patient.id)} · Cập nhật {formatDate(patient.updatedAt)}</p></div><span className="rounded-full bg-muted-bg px-2.5 py-1 text-[10px] font-bold text-muted">{STATUS_LABELS[patient.status]}</span></div><p className="mt-3 truncate text-sm text-muted">{patient.services.length ? patient.services.map(serviceLabel).join(" · ") : "Chưa chọn dịch vụ"}</p></Link>)}</div>}</section>
    <section className="mt-9 grid gap-3 sm:grid-cols-3"><Link href="/studio" className="rounded-2xl border border-border bg-card p-4 transition hover:border-accent/30"><span className="text-xl">◇</span><h3 className="mt-3 font-bold text-card-foreground">3D Consultation</h3><p className="mt-1 text-xs leading-5 text-muted">Mở baseline và phương án tư vấn.</p></Link><Link href="/gallery" className="rounded-2xl border border-border bg-card p-4 transition hover:border-accent/30"><span className="text-xl">▧</span><h3 className="mt-3 font-bold text-card-foreground">Thư viện ảnh</h3><p className="mt-1 text-xs leading-5 text-muted">Quản lý ảnh bệnh án theo hồ sơ.</p></Link><Link href="/reports" className="rounded-2xl border border-border bg-card p-4 transition hover:border-accent/30"><span className="text-xl">↗</span><h3 className="mt-3 font-bold text-card-foreground">Báo cáo tư vấn</h3><p className="mt-1 text-xs leading-5 text-muted">Xem phương án và ghi chú đã lưu.</p></Link></section>
  </div>;
}
